### ISSUE TITLE
How to patch the kernel to have 48bit Virtual address?

### ISSUE THREAD

**Issue by seisdr** [OpenKirin/android_kernel_huawei_hi6210sft#1]

**Comment by XePeleato** [comment]
May I ask why?

**Comment by ulist** [comment]
Yes . in the faqs right here https://support.huaweicloud.com/intl/en-us/ug-exagear-kunpengdevps/kunpengexagear_06_0045.html
Exagear require 48bit VA in order to work

**Comment by seisdr** [comment]
Yes . in the faqs right here https://support.huaweicloud.com/intl/en-us/ug-exagear-kunpengdevps/kunpengexagear_06_0045.html
Exagear require 48bit VA in order to work
